FROM debian:bullseye

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y libboost-dev libboost-filesystem-dev libboost-serialization-dev \
    libboost-system-dev libboost-thread-dev libboost-context-dev \
    libboost-test-dev libssl-dev g++ pkg-config python3 python3-venv \
    libluajit-5.1-dev build-essential m4 git dnsutils curl ca-certificates ragel meson virtualenv rustc cargo && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Rust (cargo)
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Install the latest Meson version
RUN pip3 install --upgrade meson

# Clone latest pdns and submodules
RUN git clone --recursive https://github.com/PowerDNS/pdns.git /pdns

WORKDIR pdns/pdns/recursordist/

# Compile the recursor
RUN meson setup builddir && \
    meson compile -C builddir -j 2 && \
    meson install -C builddir

# Copy entrypoint.sh to the correct location
COPY entrypoint.sh /pdns/entrypoint.sh
RUN chmod +x /pdns/entrypoint.sh

ENTRYPOINT ["/pdns/entrypoint.sh"]
