FROM debian:bullseye

RUN apt-get update && \
    apt-get install -y pdns-server pdns-backend-mysql curl default-mysql-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
