FROM debian:bullseye

RUN apt-get update && \
    apt-get install -y curl gnupg lsb-release && \
    curl https://repo.powerdns.com/FD380FBB-pub.asc | apt-key add - && \
    echo "deb [arch=amd64] http://repo.powerdns.com/debian $(lsb_release -cs)-auth main" > /etc/apt/sources.list.d/pdns.list && \
    apt-get update && \
    apt-get install -y pdns-server pdns-backend-mysql && \
    apt-get clean

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
