launch=gmysql
gmysql-host=mariadb
gmysql-user=pdns
gmysql-password=zaq1@WSX
gmysql-dbname=pdns
api=yes
api-key=changeme
webserver=yes
webserver-address=0.0.0.0
webserver-port=8081


local-address=0.0.0.0
local-port=53

